language: python
sudo: false
env:
  matrix:
  - LUA="lua=5.3"
  - LUA="luajit=2.1"
before_install:
- pip install hererocks
- hererocks lua_install -r^ --$LUA
- export PATH=$PATH:$PWD/lua_install/bin
install:
- luarocks install luacheck
- luarocks install busted
- luarocks install luacov
- luarocks install luacov-coveralls
script:
- luacheck main.lua ./game
- busted --run=travis
after_success:
- echo $TRAVIS_BUILD_DIR/lua_install
- luacov-coveralls --exclude ./ext --exclude $TRAVIS_BUILD_DIR/lua_install/share
before_deploy:
- cd $TRAVIS_BUILD_DIR
- zip -r -x.git/* -xlua_install/* $TRAVIS_BUILD_DIR/../terminus-$TRAVIS_TAG-$TRAVIS_BUILD_NUMBER.love
  ./
deploy:
  provider: releases
  api_key:
    secure: "MYz37jNqzTkmJFq2gavaRcWxZlTjsK8492/m0lC3kKlldsxzSVI02U+h68h7EFMlesyMEN9NmqGPC8avV4pwrnXfQt5l/xM8IN3AEX3T9neATomnKixY1xIIgVX9l284OAP/f0LUW24SmnL00ExNlgi3BnASGDQR1XafnSe8BSGBXYjlf+uBNHxfhNzz1WXO0sj7tVSiePssMF8vJoCEoiHt3oyOA8ZBCr7bdmAUFAiaTpklU3eI6Z4x7j4ekwLbx9j4l7jEpMS+qYqdosT+Nhp92FQ3QNvb54V3Ka113PyYvW5Ani/oHr8cz2+olSjsqAc0TcnEDetI15LeEebWy2prNpDgD7zdW85PTHRR4X6CzAFMGldVUnYbW27qMmTbZRM1X2wGviTFaf/BpeQAe2LMz3t4ZPsbKvbvAJu6piHWdOPdhRlBuVfPpBA69y3FcAxnXhzseorYGy4rclScW6mW7B4PrdvhlicxfXf9rDmCD++eyyokEhCYjo4fl0dglX+r6/UWw0MVxaRyzj24d/2sHonrt8hcT28M1aSlh9asKZBZhKlmSopPX6VFF+GlUwbgJZZ1VLNhbM9o75wHnoVhJl5Twwt3m2vhX0unqJ1cV8twvUxdUU/2+ENy9J3OVBhBmsUKXjCjrMyPHOwoW86XulXJ2jGmrZs3W8KA/AI="
  file: "$TRAVIS_BUILD_DIR/../terminus-$TRAVIS_TAG-$TRAVIS_BUILD_NUMBER.love"
  on:
    repo: tredfern/terminus
    tags: true
    condition: "$LUA =~ ^luajit=2.1$"
