language: python
sudo: false
env:
- LUA="lua=5.1"
- LUA="lua=5.2"
- LUA="lua=5.3"
- LUA="luajit=2.1"
before_install:
- pip install hererocks
- hererocks lua_install -r^ --$LUA
- export PATH=$PATH:$PWD/lua_install/bin
install:
- luarocks install luacheck
- luarocks install busted
- luarocks install luacov
- luarocks install luacov-coveralls
script:
- luacheck main.lua ./game
- busted --run=travis
after_success:
- echo $TRAVIS_BUILD_DIR/lua_install
- luacov-coveralls --exclude $TRAVIS_BUILD_DIR/lua_install/share --exclude ./ext
before_deploy:
- cd $TRAVIS_BUILD_DIR
- zip -r -x.git/* -xlua_install/* $TRAVIS_BUILD_DIR/../terminus-$TRAVIS_TAG-$TRAVIS_BUILD_NUMBER.love ./
deploy:
  provider: releases
  api_key:
    secure: WvPYFfGL/XF0P+EmYlxTuvsNucgmZtmeiRYwlYrIIUMyVBS0x53lgKPQv23xn2MpteTN5M7hLQhpGWiA+kJ4odA2FuHT5iRdPJys1LagmMdn7Q50wefdOmzV3UbwShuAVE+jCk72VjmaWIZlTUivL9c92EKdiMxw7ED5Fet0rBl9FIvgZe+KL3sg3DTlGjgqR5hV8wKHEhfB2BL+fjnGMhp0FRKydyllhDL9l/2+ITlHZUMgfNnmC/bmoCNrKH5JpeaoHJRu92DjC54fB40Ty1+Svb0rifLT4bnpmEn1wsI8UuAFgb0CJq4M1rFDVzNC2LBqepIGcaWFMOyV+mGNMaMlrL36zzau8YsUF50oxqpJ0xDIUbCDrlhV6Irn7SZlQjiCHKG0EEgeql13RHElZ/j7fUVveIPt6I2jARebQl/hQTyQcAx8wDBWyKBeXfFl4yFuPabpJ1sfrrxigxzVkQ8b1ag4i9h80pKRXiv1a5ewjIP4Vd6bb8qH1cobSeowxLLugVEsLIsef3z3rHqBqpbXwd5x70m4lqSvH/5A72411xJr08Fhj9Y6DEa4v05tzKlTt72E3YxRCSCEMgCtiTkjOFGzb76WcArszSC3MOZkPQSgHyJiX9IYe7Y5dnlqRo1VciYQhYuuJiV+w3DGDPmSTLyDV8YjB/3kj7YnsEs=
  file: "$TRAVIS_BUILD_DIR/../terminus-$TRAVIS_TAG-$TRAVIS_BUILD_NUMBER.love"
  on:
    repo: tredfern/terminus
    tags: true
    condition: "$LUA =~ ^luajit=2.1$"
