language: python
sudo: false
env:
  matrix:
  - LUA="lua=5.1"
  - LUA="lua=5.2"
  - LUA="lua=5.3"
  - LUA="luajit=2.1"
  global:
    secure: TrffM6NywEivArMRSo7nHVkkNpYMWKKNmOqWnhAdwG2gmtsZJm4iNVUbfh9rHCNY/Lf2E1lhSDsdXjvnWazPkGsUBuBj17Yhif+b4DQ+DDeF4tZW5gkx0Ik4xcC+Gly6eCWeHYYzUixNEN9LN190ZFb2l4lasNRa6Tv9qeSEv8PN06qLQ1HX/1Xcqqf+/LmFUwMllD/tZvtSzARd/38LruhH5N6JebFgsnV+kmjru0kDPSm16LDjapykulipJfoAtP7XF7vowIRQrLuWbz7+8oylmfNFOhWIb5a3JI8V96uxbP1HP6QkmR2dse37MPXg4bO8d5Lunc6sq2b4QgRABw4kTdh8F6RUcStD/GYYvW9IFTGI0XGaz2ApNfgT9kK5MWZcbUSqHtD2kpQrwXFCLR8Ar7dqtm8M4t+uqLEASiCwvuP3Ax+DsZ8B1xdUWxF6vUuQuyluJmOsr4D48XoEmglUxrlFzx6mEOWzH2b+aVyHxj8qB8FIng0mo2mOtMshb9hC+buWShPIRm7mdlMCpH8fIHNSMMH/NdAhtuE4sQhBTX6tlZltzf7l1FWkCLYoi0zRNWXIpe5Ujvg0sDrKX0X1XL5HxbyJgRHEmBZT9Md0cL3pxVIw267GHqJdS1hj9Op0AnVf1kPLg41zQZ6pBxTxREyjsfppP+RMdeOODlE=
before_install:
- pip install hererocks
- hererocks lua_install -r^ --$LUA
- export PATH=$PATH:$PWD/lua_install/bin
install:
- luarocks install luacheck
- luarocks install busted
- luarocks install luacov
- luarocks install luacov-coveralls
script:
- luacheck main.lua ./game
- busted --run=travis
after_success:
- echo $TRAVIS_BUILD_DIR/lua_install
- luacov-coveralls --exclude $TRAVIS_BUILD_DIR/lua_install/share --exclude ./ext
before_deploy:
- cd $TRAVIS_BUILD_DIR
- zip -r -x.git/* -xlua_install/* $TRAVIS_BUILD_DIR/../terminus-$TRAVIS_TAG-$TRAVIS_BUILD_NUMBER.love
  ./
deploy:
  provider: releases
  api_key:
    secure: $GITHUB_TOKEN
  file: "$TRAVIS_BUILD_DIR/../terminus-$TRAVIS_TAG-$TRAVIS_BUILD_NUMBER.love"
  on:
    repo: tredfern/terminus
    tags: true
    condition: "$LUA =~ ^luajit=2.1$"
