-- Copyright (c) 2020 Trevor Redfern
--
-- This software is released under the MIT License.
-- https://opensource.org/licenses/MIT

return {
  ADD = "CHARACTER_ADD",
  ADD_ITEM_TO_INVENTORY = "CHARACTER_ADD_ITEM_TO_INVENTORY",
  ATTACK = "CHARACTER_ATTACK",
  EQUIP_ITEM = "CHARACTER_EQUIP_ITEM",
  MOVE = "CHARACTER_MOVE",
  REMOVE = "CHARACTER_REMOVE",
  REMOVE_ITEM_FROM_INVENTORY = "CHARACTER_REMOVE_ITEM_FROM_INVENTORY",
  SET_HEALTH = "CHARACTER_SET_HEALTH",
  SET_NAME = "CHARACTER_SET_NAME",
  SET_POSITION = "CHARACTER_SET_POSITION",
}