-- Copyright (c) 2020 Trevor Redfern
--
-- This software is released under the MIT License.
-- https://opensource.org/licenses/MIT

return {
  ADD = "CHARACTER_ADD",
  ATTACK = "CHARACTER_ATTACK",
  BUY_ATTRIBUTE_POINT = "CHARACTER_BUY_ATTRIBUTE_POINT",
  MOVE = "CHARACTER_MOVE",
  REMOVE = "CHARACTER_REMOVE",
  SELL_ATTRIBUTE_POINT = "CHARACTER_SELL_ATTRIBUTE_POINT",
  SET_ATTRIBUTE = "CHARACTER_SET_ATTRIBUTE",
  SET_HEALTH = "CHARACTER_SET_HEALTH",
  SET_NAME = "CHARACTER_SET_NAME",
  SET_POSITION = "CHARACTER_SET_POSITION",
}