name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - uses: leafo/gh-actions-lua@v8.0.0
      with:
        luaVersion: "luajit-2.1.0-beta3"

    - uses: leafo/gh-actions-luarocks@v4.0.0

    - name: build
      run: |
        luarocks install luacheck
        luarocks install busted
        luarocks install luacov
        luarocks install luacov-coveralls
        luarocks install luafilesystem

    - name: test
      run: |
        luacheck main.lua ./game
        busted --run=travis
        luacov-coveralls --exclude ./ext --exclude /home