-- Copyright (c) 2021 Trevor Redfern
--
-- This software is released under the MIT License.
-- https://opensource.org/licenses/MIT

return {
  DEAL_DAMAGE = "COMBAT_DEAL_DAMAGE",
  MELEE_ATTACK = "COMBAT_MELEE_ATTACK",
  MELEE_ATTACK_SUCCESS = "COMBAT_MELEE_ATTACK_SUCCESS",
  MELEE_ATTACK_FAILURE = "COMBAT_MELEE_ATTACK_FAILURE",
  RANGED_ATTACK = "COMBAT_RANGED_ATTACK",
  RANGED_ATTACK_SUCCESS = "COMBAT_RANGED_ATTACK_SUCCESS",
  RANGED_ATTACK_FAILURE = "COMBAT_RANGED_ATTACK_FAILURE",
}